name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

      - name: Replace placeholders in KEYS.json
      run: |
        sed -i "s/\${PRIVATE_KEY_ID}/$PRIVATE_KEY_ID/" ./api/KEYS.json
        sed -i "s/\${PRIVATE_KEY}/$PRIVATE_KEY/" ./api/KEYS.json
        sed -i "s/\${CLIENT_ID}/$CLIENT_ID/" ./api/KEYS.json
      env:
        PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build Docker image for API
      working-directory: ./api
      run: docker build -t vikramnayyar/devops-capstone-challenge:latest .

    - name: Push Docker image for API to Docker Hub
      run: docker push vikramnayyar/devops-capstone-challenge:latest

    - name: Build Docker image for Frontend
      working-directory: ./front-end-nextjs
      run: docker build -t vikramnayyar/devops-qr-code-frontend:latest .

    - name: Push Docker image for Frontend to Docker Hub
      run: docker push vikramnayyar/devops-qr-code-frontend:latest
